"""
visualize.py
------------
Plotting and reporting utilities for the RL attack-path simulation project.

All plots are saved as PNG files in the specified output directory.
Requires: matplotlib, seaborn, pandas, numpy.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # non-interactive backend — must be called before pyplot import

import matplotlib.patches as mpatches  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import seaborn as sns  # noqa: E402

# ---------------------------------------------------------------------------
# Global style
# ---------------------------------------------------------------------------
sns.set_theme(style="whitegrid", palette="muted", font_scale=1.1)
COLORS = {"ppo": "#2196F3", "dqn": "#FF5722", "stealth": "#9C27B0", "baseline": "#4CAF50"}


# ---------------------------------------------------------------------------
# 1. Training curves (reward / episode length over timesteps)
# ---------------------------------------------------------------------------


def plot_training_curves(
    log_dir: str,
    output_dir: str = "results/plots",
    smooth_window: int = 50,
) -> None:
    """
    Plot episode reward and length curves from SB3 Monitor CSV logs.

    Parameters
    ----------
    log_dir : str
        Path containing `monitor.csv` files generated by SB3's Monitor wrapper.
    output_dir : str
        Directory where plots are saved.
    smooth_window : int
        Rolling-average window for smoothing.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    monitor_files = list(Path(log_dir).rglob("monitor.csv"))
    if not monitor_files:
        print(f"[visualize] No monitor.csv found in {log_dir}")
        return

    dfs = []
    for f in monitor_files:
        try:
            df = pd.read_csv(f, skiprows=1)
            df["source"] = f.parent.name
            dfs.append(df)
        except Exception as e:
            print(f"[visualize] Could not read {f}: {e}")
    if not dfs:
        return

    data = pd.concat(dfs, ignore_index=True)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    for col, ax, title in [
        ("r", axes[0], "Episode Reward"),
        ("l", axes[1], "Episode Length (steps)"),
    ]:
        if col not in data.columns:
            continue
        for src, grp in data.groupby("source"):
            vals = grp[col].values
            smoothed = pd.Series(vals).rolling(smooth_window, min_periods=1).mean()
            ax.plot(smoothed.values, label=src, linewidth=1.5)
        ax.set_title(title)
        ax.set_xlabel("Episode")
        ax.set_ylabel(col)
        ax.legend(fontsize=8)

    plt.suptitle("Training Curves", fontsize=14, fontweight="bold")
    plt.tight_layout()
    path = out / "training_curves.png"
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[visualize] Saved → {path}")


# ---------------------------------------------------------------------------
# 2. Attack path visualisation
# ---------------------------------------------------------------------------


def plot_attack_path(
    path: list[int],
    action_meanings: list[str] | None = None,
    title: str = "Attack Path",
    output_path: str = "results/plots/attack_path.png",
) -> None:
    """
    Visualise a sequence of actions taken by the agent as a horizontal
    timeline with colour-coded action categories.

    Parameters
    ----------
    path : list[int]
        Sequence of integer actions.
    action_meanings : list[str] or None
        Human-readable names for each action index. If None, actions are
        displayed as integers.
    title : str
        Plot title.
    output_path : str
        Where to save the PNG.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    n = len(path)
    fig, ax = plt.subplots(figsize=(max(10, n * 0.6), 3))

    category_colors = {
        "scan": "#42A5F5",
        "exploit": "#EF5350",
        "priv_esc": "#AB47BC",
        "other": "#78909C",
    }

    def _categorise(a: int, meaning: str | None) -> str:
        if meaning is None:
            return "other"
        m = meaning.lower()
        if "scan" in m:
            return "scan"
        if "exploit" in m or "e_" in m:
            return "exploit"
        if "priv" in m or "pe_" in m:
            return "priv_esc"
        return "other"

    for i, action in enumerate(path):
        meaning = action_meanings[action] if action_meanings else None
        cat = _categorise(action, meaning)
        color = category_colors[cat]
        label = meaning if meaning else str(action)
        ax.barh(0, 1, left=i, color=color, edgecolor="white", height=0.5)
        ax.text(
            i + 0.5,
            0,
            label[:10],
            ha="center",
            va="center",
            fontsize=7,
            color="white",
            fontweight="bold",
        )

    # Legend
    patches = [mpatches.Patch(color=c, label=k) for k, c in category_colors.items()]
    ax.legend(handles=patches, loc="upper right", fontsize=8)
    ax.set_xlim(0, n)
    ax.set_yticks([])
    ax.set_xlabel("Step")
    ax.set_title(title, fontweight="bold")
    plt.tight_layout()
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[visualize] Saved → {out}")


# ---------------------------------------------------------------------------
# 3. Detection sensitivity sweep
# ---------------------------------------------------------------------------


def plot_detection_sensitivity(
    thresholds: list[float],
    ppo_success_rates: list[float],
    dqn_success_rates: list[float],
    output_path: str = "results/plots/detection_sensitivity.png",
) -> None:
    """
    Plot how agent success rate varies with the detection threshold.

    Parameters
    ----------
    thresholds : list[float]
        Detection thresholds evaluated.
    ppo_success_rates : list[float]
        PPO success rate (fraction of uncaught episodes) at each threshold.
    dqn_success_rates : list[float]
        DQN success rates.
    output_path : str
        Save path.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(thresholds, ppo_success_rates, marker="o", label="PPO", color=COLORS["ppo"])
    ax.plot(thresholds, dqn_success_rates, marker="s", label="DQN", color=COLORS["dqn"])
    ax.set_xlabel("Detection Threshold")
    ax.set_ylabel("Episode Success Rate")
    ax.set_title("Agent Success vs Detection Threshold", fontweight="bold")
    ax.legend()
    ax.set_ylim(0, 1.05)
    plt.tight_layout()
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[visualize] Saved → {out}")


# ---------------------------------------------------------------------------
# 4. Comparison bar chart
# ---------------------------------------------------------------------------


def plot_comparison_bar(
    eval_results: dict[str, dict],
    output_path: str = "results/plots/comparison_bar.png",
) -> None:
    """
    Bar chart comparing key metrics between PPO and DQN (and optionally
    stealth vs baseline variants).

    Parameters
    ----------
    eval_results : dict
        Dict of form {'ppo_baseline': {...}, 'dqn_baseline': {...}, ...}
        where each value is an eval summary dict from evaluate.py.
    output_path : str
        Save path.
    """
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    metrics = ["mean_reward", "mean_steps", "success_rate", "catch_rate"]
    metric_labels = ["Mean Reward", "Mean Steps", "Success Rate", "Catch Rate"]
    agents = list(eval_results.keys())
    x = np.arange(len(metrics))
    width = 0.8 / max(len(agents), 1)

    fig, ax = plt.subplots(figsize=(12, 6))

    for i, agent in enumerate(agents):
        vals = []
        for m in metrics:
            v = eval_results[agent].get(m)
            vals.append(v if v is not None else 0.0)
        offset = (i - len(agents) / 2) * width + width / 2
        bars = ax.bar(x + offset, vals, width=width * 0.9, label=agent)
        # Value labels on bars
        for bar, val in zip(bars, vals):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.01 * max(abs(v) for v in vals if v),
                f"{val:.2f}",
                ha="center",
                va="bottom",
                fontsize=8,
            )

    ax.set_xticks(x)
    ax.set_xticklabels(metric_labels)
    ax.set_title("PPO vs DQN: Evaluation Metrics", fontweight="bold")
    ax.legend()
    plt.tight_layout()
    plt.savefig(out, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"[visualize] Saved → {out}")


# ---------------------------------------------------------------------------
# 5. Full report generator
# ---------------------------------------------------------------------------


def generate_full_report(
    results_dir: str = "results",
    output_dir: str = "results/plots",
) -> None:
    """
    Attempt to generate all standard plots from saved JSON evaluation files.

    Looks for ``eval_results.json`` and ``comparison_summary.json`` in
    `results_dir`, then calls the individual plot functions.
    """
    rdir = Path(results_dir)
    eval_path = rdir / "eval_results.json"
    comp_path = rdir / "comparison_summary.json"

    # Comparison bar chart
    if eval_path.exists():
        with open(eval_path) as f:
            eval_data = json.load(f)
        plot_comparison_bar(eval_data, output_path=str(Path(output_dir) / "comparison_bar.png"))
    elif comp_path.exists():
        with open(comp_path) as f:
            comp_data = json.load(f)
        plot_comparison_bar(comp_data, output_path=str(Path(output_dir) / "comparison_bar.png"))
    else:
        print("[visualize] No eval_results.json or comparison_summary.json found.")

    # Training curves
    for subdir in rdir.iterdir():
        if subdir.is_dir() and "monitor" not in subdir.name:
            plot_training_curves(
                log_dir=str(subdir),
                output_dir=output_dir,
            )

    print(f"\n[visualize] Full report plots saved to {output_dir}/")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    p = argparse.ArgumentParser(description="Generate evaluation plots.")
    p.add_argument("--results_dir", default="results")
    p.add_argument("--output_dir", default="results/plots")
    args = p.parse_args()
    generate_full_report(results_dir=args.results_dir, output_dir=args.output_dir)
